apiVersion: apps/v1
kind: Deployment
metadata:
  name: catstar
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catstar
  template:
    metadata:
      labels:
        app: catstar
    spec:
      containers:
      - name: catstar
        image: catherinevee/catprompt:1.04
        imagePullPolicy: "Always"
        ports:
        - containerPort: 31916
          name: http
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 400Mi
      - name: catcode
        image: catherinevee/catcode:1.03
        imagePullPolicy: "Always"
        ports:
        - containerPort: 31915
          name: http
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 400Mi
